import { StyleSheet } from "react-native";

export const countryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fafafa",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fafafa",
  },
  errorText: {
    color: "#666",
    fontSize: 16,
  },
  backgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.08,
    zIndex: -1,
  },
  flagHeader: {
    height: 280,
    overflow: "hidden",
    backgroundColor: "#fff",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  flagImage: {
    width: "100%",
    height: "100%",
  },
  contentContainer: {
    paddingHorizontal: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    marginLeft: 12,
    marginRight: 12,
  },
  headerTextContainer: {
    flex: 1,
  },
  countryName: {
    fontSize: 36,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 4,
    letterSpacing: -0.5,
  },
  miniMap: {
    width: 100,
    height: 100,
    borderRadius: 12,
    overflow: "hidden",
    marginLeft: 16,
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: "#1a1a1a",
  },
  miniMapImage: {
    width: "100%",
    height: "100%",
  },
  miniMapPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  miniMapEmoji: {
    fontSize: 24,
  },
  cardsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  dataCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 6,
    marginVertical: 8,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#1a1a1a",
  },
  cardLabel: {
    fontSize: 11,
    color: "#999",
    fontWeight: "600",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  cardValue: {
    fontSize: 16,
    color: "#1a1a1a",
    fontWeight: "700",
  },
  timeCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 6,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: "#1a1a1a",
    alignItems: "center",
  },
  timeLabel: {
    fontSize: 11,
    color: "#999",
    fontWeight: "600",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  timeDisplay: {
    fontSize: 48,
    color: "#1a1a1a",
    fontWeight: "700",
    letterSpacing: 2,
  },
  timezoneText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
    marginTop: 8,
  },
  bottomSpacer: {
    height: 20,
  },
});
